# Generated by Django 3.0.2 on 2020-02-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200222_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='download',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
